name: Java CI with Gradle

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          # Thay maven bằng gradle để máy ảo tự cache các thư viện Gradle cho nhanh
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build with Gradle
        # Lệnh này tương đương với mvn package, nó sẽ build và chạy test
        run: ./gradlew build